language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  allow_failures:
    - python: "2.7"

install:
  - pip install nose Faker codecov
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=telium test/*.py"

after_success:
  - codecov